version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        volumes:
            - .:/var/www # Mount directory ke dalam container
        networks:
            - app-network

    web:
        image: nginx:latest
        container_name: nginx_web
        ports:
            - "8000:80" # Mengakses aplikasi di port 8000
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Gunakan konfigurasi Nginx custom
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:latest
        container_name: mysql_db
        ports:
            - "3307:3306" # Mengakses database di port 3306
        environment:
            MYSQL_DATABASE: inventory_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
